name: Build and Deploy to Azure Env
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
    push:
        branches: ['master']
        workflow_dispatech:
        
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        user: actions/checkout@v3
        
      - name: Set up Docker Buildx
        user: docker/setup-buildx-action@v2
    
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: 'lindacicddemocr'
          # Container registry password
          password: 'fuAtuTg6vfg/LmI7f0FZfCAT51YPWAFR4Rx0Fv3PrF+ACRDluu6S'
          # Container registry server url
          login-server: 'lindacicddemocr.azurecr.io'
      
      - name: Build and push
           user: docker/build-push-action@v4
           with:
             push: true
             tag: lindacicddemocr.azurecr.io/hello-world-app:${{ github.sha }}
             file: ./Dockerfile

          
    deploytoAKS:
        runs-on: ubuntu-latest
        steps:
          -run: echo "hello"
